version: '3.8'

networks:
  petclinic:
    driver: bridge

services:
  app:
    image: dehado/recipes:dev
    build:
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
    ports:
      - "8080:8080"
    networks:
      - petclinic
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - ~/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=recipes
      - MYSQL_PASSWORD=recipes
      - MYSQL_DATABASE=recipes
    networks:
      - petclinic

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080
    networks:
      - petclinic
