CREATE TABLE IF NOT EXISTS RECIPE (
ID INT AUTO_INCREMENT NOT NULL,
NAME VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(255),
INGREDIENTS VARCHAR(500) NOT NULL,
DIRECTIONS VARCHAR(1000) NOT NULL,
CONSTRAINT pk_rcp_id PRIMARY KEY(ID),
CONSTRAINT uq_rcp_name_descr UNIQUE(NAME, INGREDIENTS)
)